kind: pipeline
type: docker
name: Build Gentoo Kernel

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  
trigger:
  event:
    exclude:
    - push
    - pull_request
  
steps:
- name: Build
  image: x0rzavi/gentoo-kernel:latest
  commands:
    - bash build.sh
    
- name: Upload
  image: x0rzavi/gentoo-kernel:latest
  environment: 
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
    - bash upload.sh
