kind: pipeline
type: docker
name: Build Gentoo Kernel

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  
trigger:
  event:
    exclude:
    - push
    - pull_request
  
steps:
- name: Build
  image: x0rzavi/gentoo-kernel:latest
  commands:
    - bash build.sh
    
- name: Upload
  image: x0rzavi/gentoo-kernel:latest
  commands:
    - bash upload.sh
    
- name: Publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    checksum: sha256
    files:
      - /usr/src/linux/linux.7z
      - /usr/src/linux/download_link.txt
    when:
      event: tag
