kind: pipeline
type: docker
name: Build Gentoo Kernel

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  
trigger:
  event:
    exclude:
    - push
    - pull_request
    - tag
  
steps:
- name: Build
  image: x0rzavi/gentoo-kernel:latest
  commands:
    - source ./build.sh
    
- name: Release
  image: x0rzavi/gentoo-kernel:latest
  environment: 
    GITHUB_CLI_TOKEN:
      from_secret: GITHUB_CLI_TOKEN
  commands:
    - source ./upload.sh
