name: Gentoo Kernel
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: gentoo/stage3:latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Setup
              run: source ./setup.sh
            - name: Build
              run: source ./build.sh
            - name: Release
              uses: softprops/action-gh-release@master
              with:
                files: /usr/src/linux/linux.7z
                tag_name: ${{ env.KERNEL_TAG }}
