name: Gentoo Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: bash setup.sh
      - name: Build
        run: bash build.sh
